#!/usr/bin/env python3
"""
BM-T6001: FNV-1a hash generator for Morpheus Sleep

Generates the pre-computed hashes used in morpheus.c for string-free
function resolution. Same algorithm as BM-T1001 (loader.c), case-insensitive.

Usage:
    python3 gen_hashes.py                    # print all Morpheus hashes
    python3 gen_hashes.py NtCreateFile       # hash a specific name
    python3 gen_hashes.py ntdll.dll kernel32.dll NtReadFile
"""

import sys


def hash_name(name: str) -> int:
    """Case-insensitive FNV-1a 32-bit hash, matching BM-T1001's hash_name()."""
    h = 0x9E3779B9
    for c in name.lower():
        h ^= ord(c)
        h = (h * 0x01000193) & 0xFFFFFFFF
    return h


# Functions resolved by Morpheus at runtime (via hash, no strings in binary).
# NtDelayExecution deliberately excluded — most profiled sleep primitive.
MORPHEUS_NAMES = [
    "ntdll.dll",
    "NtCreateTimer",
    "NtSetTimer",
    "NtWaitForSingleObject",
    "NtClose",
    "NtCreateEvent",
    "NtProtectVirtualMemory",
    "NtYieldExecution",
    "NtQueryPerformanceCounter",
    "RtlAllocateHeap",
    "RtlFreeHeap",
]


def print_hash(name: str) -> None:
    tag = "H_" + name.upper().replace(".", "_")
    print(f"#define {tag:40s} 0x{hash_name(name):08X}u  /* \"{name}\" */")


def main() -> None:
    names = sys.argv[1:] if len(sys.argv) > 1 else MORPHEUS_NAMES

    if names == MORPHEUS_NAMES:
        print("/* Pre-computed FNV-1a hashes for morpheus.c (BM-T1001 compatible) */")
        print("/* Generated by: python3 gen_hashes.py */")
        print()

    for name in names:
        print_hash(name)


if __name__ == "__main__":
    main()
